language: node_js
node_js:
- '9'
deploy:
  provider: heroku
  api_key:
    secure: QwnO4mTXt6xH25nELcBIUcwTJ/JuVJgbz+gmv+h0blGZqh3ZFyGdEEbdct6cvlwqFMwXB1CsV2iDNkngzObwO8OyKErH5BR+E++i1gO4k7N8/cI/SuLYXuxDyxSDvPSewTuyfAm7n6X/oAKViJP2VOQOtMy0VLCwWKMmF/v21hR7NSdj4lvWHOuR/2gTzwZWLXlWh2Zf5bIQdC5SDix57VCUAarZJZpsOLfIJs4R5kIYlF2yIGfW+wa0g64t/EURd9RFmDuQ+bPJA2w4gEIdi0BRyFnFF/A07yIxXx7PLJRsXAOutoKzlvKyWx/Kp1/SqRD9gTlu1bPaVkyFZeYWVWF2nFmi9mnmJ6SiZssqXamKFAkhletUYv5Jjbq48ZWHR/g7HrQBUgTYVOoVSr5d18ZzYscQv/S7CjnxeELagGQgcCObwOksI8tzwdr2i+KlsIIz0Dv5zQtU77fbcM/d+SYythCsgbXt7efRKRuSNAqgVfpWyfF7KTKBCnM7F9NeUOVQSDQIixGD6MVF9uC/wR4V30DL01PlLdzI5D0JoQWcuod5nSyQcaMq6EHxNv+JEnOMWRgi/ZS2GsxzW559x0GuuNt8/pBjYJWqz5TXbLAM5mqjNH2shJ8N5Am1J4PKQ6Q2VL3kSapkY2Gl2G3QrNradl9VDiEUopV9b0NiBqQ=
  app: adopt-a-corgi-api
  on:
    repo: mike-north/adopt-a-corgi-api
