language: node_js
node_js:
- '9'
deploy:
  provider: heroku
  api_key:
    secure: yBeXRWtclaKsRfjgTTpQIufZIqxphq19MAY4txHpfJTwmExfuAwFgHoM5b8sQcQ4Mo4+REcxSMnZx/R3h1SkEOpykRRmQIIhBVqq12GUXkHGL4aQPs6DGSwRjLDLrkWhDiWgsm8CW8DiqoT8Mb93bWKtBovJwKV3NMNphwc+yZ6lh1Aa547IhlcmGNbfCjni0KGNKg68u6YRgvj/TbMO8XSBT/0R2lKBAV9u9p76eNR/4SKBmdmB6IRBTGGX1KAFJPvtouojaHEA5y7X2dyrPrD7ZIvb4zETQ8SeqhmvHXyxIRjsgLf8MJ8V2fVywq73UYF1AWxVtmyzYOTk6VOYE3WP9iNtLRmRwA3MxEdPvRZ63LAHPpKuETYb4GcatZ8j40T+j38I90eOzr8Jej5NGMaGC7beyS4SUIa5gCcnAviCw7Nes/ZWhAz8kqP8nreUwFwUY/AiYArw8ZsDderjV3aJlzNhCpUJ8vLmqjtp3kiiYbz6WDa/jcSjTPQ9VytsaDIDuN2eR4E2iPVDcjYuqS5ae/duxQ5351RjpyCjk2kIIFqKtcdcoridEzIf9yKVErv1Yg422sB3Ce7KwYv9DYcVjY2OulBeyZQnf35WsdEqGNNYBaRLfdb4duboaWpCEc5JlA09+OhUxeWNkNWKG5J981Hw/YfzQA2F/CYJdVI=
  app: placecorgi-api
  on:
    repo: mike-north/placecorgi-api
